### ISSUE TITLE
Leaks when inputing spaces

### ISSUE THREAD

**Issue by IcQuackson** [abaiao-r/minishell#1]
- If inputing spaces in the terminal it shows definitely lost bytes at parser functions and print_prompt functions.

![image](https://github.com/abaiao-r/minishell/assets/61185097/14d614f5-98e9-49df-b65c-a8d1c08e60be)

**Comment by abaiao-r** [comment]
Fix whitespace input handling in validation and loading data

Description:
This commit addresses an issue where input consisting only of whitespace characters caused memory leaks and unexpected behavior in the parser and print_prompt functions. The following changes were made:

    Updated the is_input_only_whitespaces function to correctly identify if a string contains only whitespace characters.
    Modified the validate_and_load_data function to include the check for whitespace input and handle it appropriately.
    Added a call to the is_input_only_whitespaces function in the validation process to detect and handle whitespace input.

These changes ensure that whitespace input is properly validated, preventing memory leaks and improving the overall behavior of the program.
![image](https://github.com/abaiao-r/minishell/assets/118570346/37f51e54-6f00-4bf1-88e5-a3f50f011516)

> * If inputing spaces in the terminal it shows definitely lost bytes at parser functions and print_prompt functions.
> 
> 
> ![image](https://user-images.githubusercontent.com/61185097/244107588-14d614f5-98e9-49df-b65c-a8d1c08e60be.png)
