### ISSUE TITLE
Segfault redirection after pipe!

### ISSUE THREAD

**Issue by abaiao-r** [abaiao-r/minishell#4]
Segfault redirection after pipe! although the command still is executed properly.
example:
minishell: echo a | > b
creates file b with nothing inside just like bash would but there is a segfault. @IcQuackson

**Comment by abaiao-r** [comment]
@IcQuackson

**Comment by IcQuackson** [comment]
We had to not only verify that the char ** passed to exe_shell_cmd was null but also check if the pointer inside the argument was also null
