### ISSUE TITLE
SEGV on $EMPTY

### ISSUE THREAD

**Issue by IcQuackson** [abaiao-r/minishell#6]
If you type $EMPTY you get a SEGV

**Comment by abaiao-r** [comment]
fixed segfautlt when there was an expan dollar of an unexisted variable, thus causing minishell->input to be NULL. #6

![image](https://github.com/abaiao-r/minishell/assets/118570346/2034dfa4-de7e-4902-a375-4117f291d9d3)
now we check if minishell->input exists.
